name: Run tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
      - name: Run e2e tests
        uses: cypress-io/github-action@master
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:8080/
