name: Run tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing dependencies
        run: npm install
      - name: Running unit tests
        run: npm run test:unit
      - name: Running e2e tests
        run: npm run test:e2e
